#!/usr/bin/env python3
"""
Refreshes the Port of Los Angeles daily gate success rates.

POLA publishes "Daily Fulfilled Truck Gates by Terminal" as a PDF, updated each
weekday, free and without registration. It reports, per terminal, the share of
booked truck appointments that were actually fulfilled — the closest thing to a
published per-terminal congestion measure for San Pedro Bay that anyone can read
without a commercial contract.

    python3 scripts/fetch_pola_gate_success.py

Writes src/data/polaGateSuccess.js.

Two deliberate limits:

  * Only the percentages are read. The chart's bars carry capacity and fulfilled
    counts, but the PDF text layer does not make their pairing unambiguous, and
    guessing it would put invented numbers back into the app.
  * If the layout changes, this fails loudly rather than emitting something
    plausible. A silent wrong number is the failure mode that matters here.
"""

import json
import re
import urllib.request
import zlib
from datetime import datetime, timezone
from pathlib import Path

SOURCE = ("https://portoflosangeles.org/getmedia/"
          "e7e35d31-c560-49fe-be52-f335412879e8/fulfilled-truck-gates")

# Terminal labels as printed in the PDF, mapped to this project's ids.
# POLA reports West Basin as a single figure covering both of its terminals.
LABEL_TO_IDS = {
    "APMT": ["T-APM"],
    "TraPac": ["T-TRP"],
    "ETS": ["T-EVP"],
    "WBCT": ["T-WBCT-CS", "T-WBCT-TIL"],
    "FMS": ["T-FMS"],
    "YTI": ["T-YTI"],
}


def extract_text(pdf: bytes) -> str:
    """Text-showing operators only, so image and font data stay out."""
    out = []
    for m in re.finditer(rb"stream\r?\n(.*?)endstream", pdf, re.S):
        raw = m.group(1)
        try:
            body = zlib.decompress(raw)
        except zlib.error:
            body = raw
        for op in re.findall(rb"\((?:\\.|[^\\()])*\)\s*Tj|\[(?:[^\]\\]|\\.)*\]\s*TJ", body):
            joined = b"".join(re.findall(rb"\((?:\\.|[^\\()])*\)", op))
            joined = re.sub(rb"[()]", b"", joined)
            if joined.strip():
                out.append(joined.decode("latin-1", "replace"))
    return re.sub(r"\s+", " ", " ".join(out))


req = urllib.request.Request(SOURCE, headers={"User-Agent": "Mozilla/5.0"})
pdf = urllib.request.urlopen(req, timeout=60).read()
text = extract_text(pdf)

date_m = re.search(r"Data From ([A-Z][a-z]+ \d{1,2}, \d{4})", text)
if not date_m:
    raise SystemExit("Could not find the 'Data From <date>' line — PDF layout changed.")

block = text[text.index("Daily Gate Success Rate"):]
labels = re.findall(r"\b(APMT|TraPac|ETS|WBCT|FMS|YTI)\b", block)
pcts = [int(p) for p in re.findall(r"(\d+)%", block)]

if len(labels) != 6 or len(pcts) < 7:
    raise SystemExit(f"Unexpected layout: {len(labels)} labels, {len(pcts)} percentages.")

by_terminal = {}
for label, pct in zip(labels, pcts):
    for tid in LABEL_TO_IDS[label]:
        by_terminal[tid] = pct

payload = {
    "source": SOURCE,
    "publisher": "Port of Los Angeles — Daily Fulfilled Truck Gates by Terminal",
    "dataDate": date_m.group(1),
    "capturedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "metric": "gateSuccessRatePct",
    "meaning": ("Share of booked truck appointments actually fulfilled that day. "
                "Low means the terminal could not take the trucks booked for it. "
                "Above 100% means it processed more than its estimated capacity."),
    "allTerminals": pcts[-1],
    "byTerminal": by_terminal,
}

header = '''/**
 * PUBLISHED GATE SUCCESS RATES — Port of Los Angeles container terminals.
 *
 * Generated by scripts/fetch_pola_gate_success.py. Do not hand-edit.
 *
 * POLA publishes the share of booked truck appointments actually fulfilled at
 * each terminal, each weekday, free and without registration. A low rate means
 * the terminal could not take the trucks that were booked for it; above 100%
 * means it worked beyond its estimated capacity.
 *
 * This is a real published measure of how a terminal is coping. It is NOT a
 * queue length and NOT a turn time — neither is published free — and must not
 * be presented as either.
 *
 * Long Beach publishes no equivalent, so POLB terminals are absent here and
 * report as unknown. Long Beach instead publishes a gate calendar, which lives
 * in polbGateCalendar.js. Between them the two ports give one real signal each,
 * of different kinds, and neither is filled in for the other.
 */

'''
dest = Path(__file__).resolve().parent.parent / "src" / "data" / "polaGateSuccess.js"
dest.write_text(header + "export const POLA_GATE_SUCCESS = " + json.dumps(payload, indent=2) + "\n")

print(f"wrote {dest.relative_to(Path.cwd())} — data from {payload['dataDate']}")
print(f"  all terminals: {payload['allTerminals']}%")
for tid, v in by_terminal.items():
    print(f"  {tid:<12} {v}%")
