#!/usr/bin/env node
/**
 * Pulls live Port of Long Beach operating data from CargoNav.
 *
 * CargoNav is POLB's own operational data hub. Its Operations Dashboard is a
 * Vue app on dashboard.cargonav.polb.com backed by core-api.port-scih.com, and
 * those chart endpoints are open: no key, no auth, plain server-side fetch.
 *
 * That matters because it replaces guesswork with measurement. The endpoint
 * `average-terminal-gate-turn-time` publishes, per terminal, the actual average
 * minutes a truck spends inside the gate, split day and night. This project
 * previously asserted that no such figure was published free. It was wrong; the
 * figure was one layer below the page being read.
 *
 *   node scripts/fetch_cargonav.mjs
 *
 * Writes src/data/cargonav.js. Fails loudly on a shape change rather than
 * emitting something plausible.
 */

import { writeFileSync } from 'node:fs'

const BASE = 'https://core-api.port-scih.com'

/** CargoNav's terminal labels, mapped to this project's terminal ids. */
const LOCATION_TO_ID = {
  'Pier A - SSA Marine': 'T-SSA-A',
  'Pier C - SSA Marine': 'T-SSA-C',
  'Pier E - Long Beach Container Terminal (LBCT)': 'T-LBCT',
  'Pier G - International Transportation Service (ITS)': 'T-ITS',
  'Pier J - Pacific Container Terminal (PCT)': 'T-PCT',
  'Pier T - Total Terminals International (TTI)': 'T-TTI',
}

async function get(path) {
  const res = await fetch(BASE + path, {
    headers: {
      Accept: 'application/json',
      'User-Agent': 'drayage-ops-map (https://github.com/elijahpaz/InteractiveMap)',
    },
  })
  if (!res.ok) throw new Error(`${path} → ${res.status}`)
  return res.json()
}

const [turn, berth, dwell, flow] = await Promise.all([
  get('/v1/charts/average-terminal-gate-turn-time'),
  get('/v1/charts/vessels-at-berth'),
  get('/v2/charts/dwell-by-day'),
  get('/v2/charts/terminal-flow-truck-activity'),
])

if (!Array.isArray(turn?.averageTerminalGateTurnTimes)) {
  throw new Error('Turn-time payload shape changed — refusing to write.')
}

const turnByTerminal = {}
for (const row of turn.averageTerminalGateTurnTimes) {
  const id = LOCATION_TO_ID[row.location]
  if (!id) {
    console.warn(`  unmapped CargoNav location: ${row.location}`)
    continue
  }
  turnByTerminal[id] = { dayMinutes: row.dayMinutes, nightMinutes: row.nightMinutes }
}

const mapped = Object.keys(turnByTerminal).length
if (mapped !== Object.keys(LOCATION_TO_ID).length) {
  throw new Error(`Mapped ${mapped} of ${Object.keys(LOCATION_TO_ID).length} terminals — labels changed?`)
}

// Import dwell: the share of boxes sitting nine days or more is the clearest
// single read on whether the yard is backing up.
const lastIdx = (dwell?.labels?.length ?? 0) - 1
const dwellLatest =
  lastIdx >= 0
    ? {
        date: dwell.labels[lastIdx],
        d0to3: Number(dwell.dwell0To3?.[lastIdx] ?? 0),
        d4to8: Number(dwell.dwell4To8?.[lastIdx] ?? 0),
        d9to12: Number(dwell.dwell9To12?.[lastIdx] ?? 0),
        d13plus: Number(dwell.dwell13To999?.[lastIdx] ?? 0),
      }
    : null

// Truck transactions through the gates, per day. Complex-wide rather than per
// terminal, but it is a count of real moves, not an estimate: how many trucks
// actually got in and out. The weekend collapse in it is a useful sanity check
// that the feed is live.
const truckFlow = Array.isArray(flow?.flowDate)
  ? flow.flowDate.map((d, i) => {
      const loadedIn = Number(flow.loadedIn?.[i] ?? 0)
      const loadedOut = Number(flow.loadedOut?.[i] ?? 0)
      const emptyIn = Number(flow.emptyIn?.[i] ?? 0)
      const emptyOut = Number(flow.emptyOut?.[i] ?? 0)
      return {
        date: d.slice(0, 10),
        loadedIn,
        loadedOut,
        emptyIn,
        emptyOut,
        total: loadedIn + loadedOut + emptyIn + emptyOut,
      }
    })
  : []

const payload = {
  source: `${BASE}/v1/charts/average-terminal-gate-turn-time`,
  publisher: 'Port of Long Beach — CargoNav Operations Dashboard',
  dashboard: 'https://dashboard.cargonav.polb.com/',
  capturedAt: new Date().toISOString().replace(/\.\d+Z$/, 'Z'),
  turnTime: {
    asOf: turn.date,
    unit: 'minutes',
    meaning:
      'Average time a truck spends inside the terminal gate, measured by the port. Day and night shifts reported separately.',
    byTerminal: turnByTerminal,
  },
  vesselsAtBerth: Array.isArray(berth?.data) ? berth.data.length : null,
  importDwell: dwellLatest,
  truckFlow: {
    unit: 'gate transactions',
    meaning:
      'Truck moves through Long Beach gates per day, counted by the port. Complex-wide, not per terminal.',
    days: truckFlow,
  },
}

const header = `/**
 * LIVE OPERATING DATA — Port of Long Beach, via CargoNav.
 *
 * Generated by scripts/fetch_cargonav.mjs. Do not hand-edit.
 *
 * CargoNav is POLB's own operational data hub, and its chart API is open —
 * no key, no auth. Everything below is measured and published by the port.
 *
 *   turnTime   Average minutes a truck spends inside the gate, per terminal,
 *              day and night. This is a real measurement, not a proxy: it is
 *              the congestion figure this project previously claimed was not
 *              published anywhere free.
 *
 *   importDwell  How long import boxes are sitting, bucketed by age. A rising
 *                nine-day-plus share means the yard is backing up.
 *
 *   truckFlow    Truck moves through the gates per day, counted by the port —
 *                loaded and empty, in and out. Complex-wide, not per terminal.
 *
 * Los Angeles publishes no equivalent turn time, so POLA terminals fall back to
 * appointment fulfilment in polaGateSuccess.js. Neither port's figure is ever
 * used to fill in for the other.
 */

`
writeFileSync(
  new URL('../src/data/cargonav.js', import.meta.url),
  header + 'export const CARGONAV = ' + JSON.stringify(payload, null, 2) + '\n'
)

console.log(`wrote src/data/cargonav.js — turn times as of ${turn.date.slice(0, 10)}`)
for (const [id, t] of Object.entries(turnByTerminal)) {
  console.log(`  ${id.padEnd(10)} ${String(t.dayMinutes).padStart(3)}m day  ${String(t.nightMinutes).padStart(3)}m night`)
}
const busy = truckFlow.filter((d) => d.total > 2000)
if (busy.length) {
  const avg = Math.round(busy.reduce((a, d) => a + d.total, 0) / busy.length)
  console.log(`  truck transactions: ${avg.toLocaleString()}/weekday over ${truckFlow.length} days`)
}
if (dwellLatest) {
  const total = dwellLatest.d0to3 + dwellLatest.d4to8 + dwellLatest.d9to12 + dwellLatest.d13plus
  console.log(`  import dwell 9d+: ${Math.round(((dwellLatest.d9to12 + dwellLatest.d13plus) / total) * 100)}% of ${total.toLocaleString()} boxes`)
}
